name: mac-osx
description: template used to build for mac osx

inputs:
 vcpkg_installed_folder:
    required: true
    type: string
 vcpkg_arch:
    required: true
    type: string
 xcode_arch:
    required: true
    type: string

runs:
    using: "composite"
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Tools
      run: brew install nasm
      shell: bash
      
    - name: Vcpkg Integration
      run: $VCPKG_INSTALLATION_ROOT/vcpkg integrate install
      shell: bash
      
    - name: Get Vcpkg current hash
      run: echo "vcpkg_current_hash=$(git -C $VCPKG_INSTALLATION_ROOT rev-parse --short HEAD)" >> $GITHUB_ENV
      shell: bash
      
    - name: Cache Vcpkg
      uses: actions/cache@v3
      with:
        path: vcpkg/${{inputs.vcpkg_installed_folder}}
        key: ${{runner.os}}-${{inputs.vcpkg_installed_folder}}-${{env.vcpkg_current_hash}}-${{hashFiles('**/vcpkg.json')}}
      
    - name: Switch to Xcode 13.4.1
      run: sudo xcode-select --switch /Applications/Xcode_13.4.1.app
      shell: bash
      
    - name: Install Dependencies
      run: cd vcpkg && ./install-${{inputs.vcpkg_arch}}-osx.sh
      shell: bash
      
    - name: Build
      run: cd PBProjects && xcodebuild -arch ${{inputs.xcode_arch}} -target "Aleph One" DEVELOPMENT_TEAM='' CODE_SIGN_IDENTITY='-' CODE_SIGN_STYLE='Automatic' build
      shell: bash