name: CI-build

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure
      uses: ./.github/actions/configure-linux
    - name: Build
      run: make -j 2
      
  mac-osx-x64:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: ./.github/actions/build-mac-osx
        with:
          vcpkg_installed_folder: installed-x64-osx
          vcpkg_arch: x64
          xcode_arch: x86_64
          
  mac-osx-arm:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: ./.github/actions/build-mac-osx
        with:
          vcpkg_installed_folder: installed-arm64-osx
          vcpkg_arch: arm
          xcode_arch: arm64
          
  windows-x64:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: ./.github/actions/build-windows
        with:
          platform: x64
          vcpkg_installed_folder: installed-x64-windows
          
  windows-x86:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: ./.github/actions/build-windows
        with:
          platform: x86
          vcpkg_installed_folder: installed-x86-windows