name: release-mac-osx

on: [workflow_dispatch, workflow_call]

jobs:
  release:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        
    - name: Build
      uses: ./.github/actions/build-mac-osx
      with:
        xcode_targets: "Aleph One, Marathon, Marathon 2, Marathon Infinity"

    - name: Create DMGs
      run: cd tools && ./build_dmg.sh $GITHUB_WORKSPACE $GITHUB_WORKSPACE/PBProjects/build/Release
      
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: alephone-macos-release
        if-no-files-found: error
        path: 'PBProjects/build/Release/*.dmg'
