name: release-linux

on: [workflow_dispatch, workflow_call]

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        
    - name: Configure
      uses: ./.github/actions/configure-linux
        
    - run: make dist
    - uses: actions/upload-artifact@v3
      with:
        name: alephone-release
        if-no-files-found: error
        path: '*.tar.bz2'
          
    - run: make datadist
    - uses: actions/upload-artifact@v3
      with:
        name: alephone-release
        if-no-files-found: error
        path: '*.zip'